# Use Python 3.9 image
FROM python:3.9

# Set working directory in container
WORKDIR /app

# Copy all student files into container
COPY . .

# Run app.py when container starts
CMD ["python", "app.py"]